MvcUniversity/Models/ErrorViewModel.cs
using System;

namespace MvcUniversity.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcUniversity/Models/JsonModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcUniversity.Models
{
    public class JsonModel
    {

        public class Options { 
            public string[] gender { get; set; }
            
            public string[] yearLevel { get; set; }
        }
    }
}

MvcUniversity/Models/Student.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MvcUniversity.Models
{
    public class Student
    {
        [Key]
        public int id { get; set; }

        [DisplayName("Student LRN")]
        public string StudLRN { get; set; }
        
        [DisplayName("Full Name")]
        [Required]
        public string FullName { get; set; }

        [DisplayName("Course")]
        [Required]
        public string StudCourse { get; set; }

        [DisplayName("Year")]
        [Required]
        public int StudYear { get; set; }

        [DisplayName("Section")]
        [Required]
        public string StudSection { get; set; }

    }
}

MvcUniversity/Models/Teacher.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace MvcUniversity.Models
{
    public class Teacher
    {
        [Key]
        public int Id { get; set; }

        [DisplayName("Full Name")]
        [Required]
        public string Fullname { get; set; }

        [DisplayName("Current Address")]
        [Required]
        public string Address { get; set; }

        [DisplayName("Email")]
        [Required]
        public string Email { get; set; }

        [Required]
        public int Phone { get; set; }

        [Required]
        public string Birthday { get; set; }

        [Required]
        public string Gender { get; set; }

        [Required]
        public string Course { get; set; }

        [Required]
        public string Level { get; set; }

        [DisplayName("Profile Picture")]
        [Required]
        public string ProfileImage { get; set; }
    }
}

MvcUniversity/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MvcUniversity.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MvcUniversity.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcUniversity/Controllers/StudentsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MvcUniversity.Data;
using MvcUniversity.Models;

namespace MvcUniversity.Controllers
{
    public class StudentsController : Controller
    {
        private readonly MvcUniversityDbContext _db;
        private IEnumerable<Student> objStudents;

        public StudentsController(MvcUniversityDbContext db)
        {
            this._db = db;
            this.objStudents = _db.Student;
        }

        public IActionResult Index()
        {
            return View(this.objStudents);
        }

        public IActionResult AddStudent() {
            ViewBag.studLRN = Int64.Parse(this.objStudents.Last().StudLRN) + 1;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddStudent(Student obj) {
            ViewBag.studLRN = Int64.Parse(this.objStudents.Last().StudLRN) + 1;

            if ( !ModelState.IsValid ) { return View(obj); } //return if not valid

            _db.Student.Add(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }


        public IActionResult Edit(int? id) {
            if (id == null || id == 0) { return NotFound(); }

            var studToEdit = _db.Student.Find(id);
            if (studToEdit == null) { return NotFound();  }

            return View(studToEdit);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Student obj) {

            if (!ModelState.IsValid) { return View(obj);  }

            _db.Student.Update(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0) { return NotFound(); }

            var studToDel = _db.Student.Find(id);
            if (studToDel == null) { return NotFound(); }

            return View(studToDel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteStudent(int? id)
        {
            if (id == null || id == 0) { return NotFound(); }

            var studToDel = _db.Student.Find(id);
            if (studToDel == null) { return NotFound(); }

            _db.Student.Remove(studToDel);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcUniversity/Controllers/TeachersController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MvcUniversity.Data;
using MvcUniversity.Models;
using Newtonsoft.Json;
using System.IO;

namespace MvcUniversity.Controllers
{
    public class TeachersController : Controller
    {
        private readonly MvcUniversityDbContext _db;
        private IEnumerable<Teacher> teachers;
        private JsonOptions jsonOptions;

        public TeachersController(MvcUniversityDbContext db)
        {
            this._db = db;
            this.teachers = this._db.Teacher;
            this.jsonOptions = JsonConvert.DeserializeObject<JsonOptions>("");
        }
        public IActionResult Index()
        {
            return View(this.teachers);
        }

        public IActionResult Edit() {

            return View();
        }
    }
}

MvcUniversity/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcUniversity/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcUniversity</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" />
 </head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcUniversity</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Students" asp-action="Index">Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teachers" asp-action="Index">Teachers</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MvcUniversity - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MvcUniversity/Views/Students/AddStudent.cshtml
@model MvcUniversity.Models.Student;


<form method="post" asp-action="AddStudent">
    <div class="border p-3">
        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
        <div class="form-group row">
            <h2 class="text-info pl-3">
                Add Student
            </h2>
        </div>
        <div class="form_fields">
            <div class="row form-group fgr-field">
                <div class="col-4">
                    <label asp-for="StudLRN">Studen LRN</label>
                </div>
                <div class="col-8">
                    <input type="text" asp-for="StudLRN" class="form-control" value="@ViewBag.studLRN" readonly />
                </div>
            </div>
            <div class="row form-group fgr-field">
                <div class="col-4">
                    <label asp-for="FullName">Fullname</label>
                </div>
                <div class="col-8">
                    <input type="text" asp-for="FullName" class="form-control" />
                    <span class="text-danger" asp-validation-for="FullName"></span>
                </div>
            </div>
            <div class="row form-group fgr-field">
                <div class="col-4">
                    <label asp-for="StudCourse">Course</label>
                </div>
                <div class="col-8">
                    <input type="text" asp-for="StudCourse" class="form-control" />
                    <span class="text-danger" asp-validation-for="StudCourse"></span>
                </div>
            </div>
            <div class="row form-group fgr-field">
                <div class="col-4">
                    <label asp-for="StudYear">Year</label>
                </div>
                <div class="col-8">
                    <input type="text" asp-for="StudYear" class="form-control" />
                    <span class="text-danger" asp-validation-for="StudYear"></span>
                </div>
            </div>
            <div class="row form-group fgr-field">
                <div class="col-4">
                    <label asp-for="StudSection">Section</label>
                </div>
                <div class="col-8">
                    <input type="text" asp-for="StudSection" class="form-control" />
                    <span class="text-danger" asp-validation-for="StudSection"></span>
                </div>
            </div>
        </div>
        <div class="form-footer">
            <div class="form-group row">
                <div class="col-8 offset-4 row">
                    <div class="col pl-0">
                        <input type="submit" name="add-student" class="btn btn-info w-100" value="Add Student" />
                    </div>
                    <div class="col">
                        <a class="btn btn-primary" asp-action="Index"><i class="fa-solid fa-caret-left"></i> Back</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>


@section Scripts{ <!-- adding Javascript -->

    <!--  include _ValidationScriptsPartial for client validation -->
    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

MvcUniversity/Views/Students/Delete.cshtml
@model MvcUniversity.Models.Student;


<form method="post" asp-action="DeleteStudent">
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-info pl-3">
                <i class="fa-solid fa-trash"></i> Delete Student
            </h2>
        </div>
        <div class="form_fields">
            <div class="row form-group fgr-field">
                <div class="col-4">
                    <label asp-for="StudLRN">Studen LRN</label>
                </div>
                <div class="col-8">
                    <input type="text" asp-for="StudLRN" class="form-control" readonly />
                </div>
            </div>
            <div class="row form-group fgr-field">
                <div class="col-4">
                    <label asp-for="FullName">Fullname</label>
                </div>
                <div class="col-8">
                    <input type="text" asp-for="FullName" class="form-control" readonly/>
                    <span class="text-danger" asp-validation-for="FullName"></span>
                </div>
            </div>
            <div class="row form-group fgr-field">
                <div class="col-4">
                    <label asp-for="StudCourse">Course</label>
                </div>
                <div class="col-8">
                    <input type="text" asp-for="StudCourse" class="form-control" readonly/>
                    <span class="text-danger" asp-validation-for="StudCourse"></span>
                </div>
            </div>
            <div class="row form-group fgr-field">
                <div class="col-4">
                    <label asp-for="StudYear">Year</label>
                </div>
                <div class="col-8">
                    <input type="text" asp-for="StudYear" class="form-control" readonly/>
                    <span class="text-danger" asp-validation-for="StudYear"></span>
                </div>
            </div>
            <div class="row form-group fgr-field">
                <div class="col-4">
                    <label asp-for="StudSection">Section</label>
                </div>
                <div class="col-8">
                    <input type="text" asp-for="StudSection" class="form-control" readonly/>
                    <span class="text-danger" asp-validation-for="StudSection"></span>
                </div>
            </div>
            <input asp-for="id" hidden />
        </div>
        <div class="form-footer">
            <div class="form-group row">
                <div class="col-8 offset-4 row">
                    <div class="col pl-0">
                        <input type="submit" name="add-student" class="btn btn-danger w-100" value="Delete Student" />
                    </div>
                    <div class="col">
                        <a class="btn btn-primary" asp-action="Index"><i class="fa-solid fa-caret-left"></i> Back</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>


@section Scripts{ <!-- adding Javascript -->
    <!--  include _ValidationScriptsPartial for client validation -->
    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

MvcUniversity/Views/Students/Edit.cshtml
@model MvcUniversity.Models.Student;


<form method="post" >
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-info pl-3">
                <i class="fa-solid fa-pen"></i> Edit Student
            </h2>
        </div>
        <div class="form_fields">
            <div class="row form-group fgr-field">
                <div class="col-4">
                    <label asp-for="StudLRN">Studen LRN</label>
                </div>
                <div class="col-8">
                    <input type="text" asp-for="StudLRN" class="form-control" readonly />
                </div>
            </div>
            <div class="row form-group fgr-field">
                <div class="col-4">
                    <label asp-for="FullName">Fullname</label>
                </div>
                <div class="col-8">
                    <input type="text" asp-for="FullName" class="form-control" />
                    <span class="text-danger" asp-validation-for="FullName"></span>
                </div>
            </div>
            <div class="row form-group fgr-field">
                <div class="col-4">
                    <label asp-for="StudCourse">Course</label>
                </div>
                <div class="col-8">
                    <input type="text" asp-for="StudCourse" class="form-control" />
                    <span class="text-danger" asp-validation-for="StudCourse"></span>
                </div>
            </div>
            <div class="row form-group fgr-field">
                <div class="col-4">
                    <label asp-for="StudYear">Year</label>
                </div>
                <div class="col-8">
                    <input type="text" asp-for="StudYear" class="form-control" />
                    <span class="text-danger" asp-validation-for="StudYear"></span>
                </div>
            </div>
            <div class="row form-group fgr-field">
                <div class="col-4">
                    <label asp-for="StudSection">Section</label>
                </div>
                <div class="col-8">
                    <input type="text" asp-for="StudSection" class="form-control" />
                    <span class="text-danger" asp-validation-for="StudSection"></span>
                </div>
            </div>
            <input asp-for="id"  hidden />
        </div>
        <div class="form-footer">
            <div class="form-group row">
                <div class="col-8 offset-4 row">
                    <div class="col pl-0">
                        <input type="submit" name="add-student" class="btn btn-info w-100" value="Update Student" />
                    </div>
                    <div class="col">
                        <a class="btn btn-primary" asp-action="Index"><i class="fa-solid fa-caret-left"></i> Back</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>


@section Scripts{ <!-- adding Javascript -->
    <!--  include _ValidationScriptsPartial for client validation -->
    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

MvcUniversity/Views/Students/Index.cshtml
@model IEnumerable<MvcUniversity.Models.Student>

<div class="category-wrapper">
    <div class="container">
        <div class="row py-2">
            <div class="col-6">
                <h2 class="text-primary">Student List</h2>
            </div>
            <div class="col-6">
                <a class="btn btn-primary" asp-controller="Students" asp-action="AddStudent">
                    <i class="fa-solid fa-plus"></i> Add New Student
                </a>
            </div>
        </div>
        @if (Model.Count() > 0)
        {
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>LRN</th>
                        <th>Fullname</th>
                        <th>Course</th>
                        <th>Year</th>
                        <th>Section</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var studObj in Model)
                    {
                    <tr>
                        <td width="10%">@studObj.StudLRN</td>
                        <td width="40%">@studObj.FullName</td>
                        <td width="10%">@studObj.StudCourse</td>
                        <td width="10%">@studObj.StudYear</td>
                        <td width="10%">@studObj.StudSection</td>
                        <td width="20%" class="text-center">
                            <div class="btn-group" role="group">
                            <a class="btn btn-info mx-1" asp-route-id="@studObj.id" asp-controller="Students" asp-action="Edit"><i class="fa-solid fa-pen"></i></a>
                            <a class="btn btn-danger mx-1" asp-route-id="@studObj.id" asp-controller="Students" asp-action="Delete"><i class="fa-solid fa-trash"></i></a>
                            </div>
                        </td>
                    </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <p>No category found</p>
        }
    </div>
</div>

MvcUniversity/Views/Teachers/Edit.cshtml
@model MvcUniversity.Models.Teacher;

<form method="post">
    <div class="border p-3">
        <div class="row page-header">
            <h1 class="text-info"> <i class="fa-solid fa-pen"></i>  Edit Section</h1>
        </div>
        <div class="form-fields">
            <div class="row form-group fgr-field">
                <div class="col-4">
                    <label asp-for="Fullname"></label>
                </div>
                <div class="col-8">
                    <input type="text" asp-for="Fullname" class="form-control" />
                </div>
            </div>
            <div class="row form-group fgr-field">
                <div class="col-4">
                    <label asp-for="Address"></label>
                </div>
                <div class="col-8">
                    <input type="text" asp-for="Address" class="form-control" />
                </div>
            </div>
            <div class="row form-group fgr-field">
                <div class="col-4">
                    <label asp-for="Email"></label>
                </div>
                <div class="col-8">
                    <input type="text" asp-for="Email" class="form-control" />
                </div>
            </div>
            <div class="row form-group fgr-field">
                <div class="col-4">
                    <label asp-for="Phone"></label>
                </div>
                <div class="col-8">
                    <input type="text" asp-for="Phone" class="form-control" />
                </div>
            </div>
            <div class="row form-group fgr-field">
                <div class="col-4">
                    <label asp-for="Birthday"></label>
                </div>
                <div class="col-8">
                    <input type="text" asp-for="Birthday" class="form-control" />
                </div>
            </div>
            <div class="row form-group fgr-field">
                <div class="col-4">
                    <label asp-for="Gender"></label>
                </div>
                <div class="col-8">
                    <select class="form-select form-control">
                        <option selected>Please select...</option>

                    </select>
                </div>
            </div>
        </div>
    </div>
</form>

MvcUniversity/Views/Teachers/Index.cshtml
@model IEnumerable<MvcUniversity.Models.Teacher>

<div class="category-wrapper">
    <div class="container">
        <div class="row py-2">
            <div class="col-6">
                <h2 class="text-primary">Teacher List</h2>
            </div>
            <div class="col-6">
                <a class="btn btn-primary" asp-controller="Teachers" asp-action="Add">
                    <i class="fa-solid fa-plus"></i> Add New Teacher
                </a>
            </div>
        </div>
        @if (Model.Count() > 0)
        {
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Fullname</th>
                        <th>Address</th>
                        <th>Email</th>
                        <th>Phone</th>
                        <th>Level</th>
                        <th>Course</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var teacherObj in Model)
                    {
                    <tr>
                        <td width="20%">@teacherObj.Fullname</td>
                        <td width="20%">@teacherObj.Address</td>
                        <td width="10%">@teacherObj.Email</td>
                        <td width="10%">@teacherObj.Phone</td>
                        <td width="10%">@teacherObj.Level</td>
                        <td width="20%">@teacherObj.Course</td>
                        <td width="10%" class="text-center">
                            <div class="btn-group" role="group">
                                <a class="btn btn-info mx-1" asp-route-id="@teacherObj.Id" asp-controller="Teachers" asp-action="Edit"><i class="fa-solid fa-pen"></i></a>
                                <a class="btn btn-danger mx-1" asp-route-id="@teacherObj.Id" asp-controller="Teachers" asp-action="Delete"><i class="fa-solid fa-trash"></i></a>
                            </div>
                        </td>
                    </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <p>No category found</p>
        }
    </div>
</div>